spring:
  application:
    name: eureka-sv
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.5
        max-attempts: 6
  config:
    import: configserver:http://localhost:8081


