spring:
  application:
    name: sales-service
  cloud:
    config:
      fail-fast: true 
      retry:
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.5
        max-attempts: 3
  config:
    import: configserver:http://localhost:8081